# Generated by Django 6.0.1 on 2026-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cane_crush', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp notification was sent to customer'),
        ),
    ]
